### ISSUE TITLE
Link to https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/...

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-intro#57]
Page https://redhatquickcourses.github.io/rhods-intro/rhods-intro/1.33/chapter3/section3.html has sentence

> For more information about notebook images, refer to the [Notebook images for data scientists section in the Red Hat OpenShift AI documentation](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/1/html-single/working_on_data_science_projects/index#notebook-images-for-data-scientists_notebooks).

which links to (under) https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/...

That location redirects to the new location https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_cloud_service/...

It'd be good to avoid relying on that redirect on access.redhat.com and link to the desired location directly.

**Comment by rsriniva** [comment]
thank you for reporting this @adelton - It's annoying when documentation links are broken without regard to publicly published links. We just changed it a few months back due to the product renaming, and now again it was broken. 

We tried to avoid direct linking and just mention "refer to section xxx" in the "YYY" guide, but some users complained that this is not very user friendly. que sera sera.....

anyway, link fixed in main.
